server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/voice_prescription_db
spring.datasource.username=root
spring.datasource.password=gokul@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# VERY IMPORTANT FOR REVIEW
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

# You can remove this (optional - Hibernate auto detects)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=SuperSecretKeyForJwtGeneration12345678901234567890
jwt.expiration=86400000

spring.security.filter.dispatcher-types=request